### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by minaayman** [minaayman/ASUMobiCarG18#2]
search about bluetooth module hc-05

**Comment by Nadern96** [comment]
//To connect the blutooth Module to arduino
Arduino Pins           Bluetooth Pins
RX (Pin 0)     ———->      TX
TX (Pin 1)      ———->      RX
5V                ———->      VCC
GND             ———->      GND

//Function we need in our code to deal with bluetooth module is:
- serial.begin(9600); // Sets the baud for serial data transmission                   
-if(Serial.available() > 0)      // Send data only when you receive data:
data = Serial.read();        //Read the incoming data & store into data

**Comment by NaderYousab** [comment]
task accomplished 💯
